#include "../mpconfigport.h"

#undef MICROPY_CONFIG_ROM_LEVEL
#define MICROPY_CONFIG_ROM_LEVEL (MICROPY_CONFIG_ROM_LEVEL_EXTRA_FEATURES)

#define MICROPY_PY_ASYNCIO (1)
#define MICROPY_PY_NETWORK (1)
#define MICROPY_PY_NETWORK_HOSTNAME_DEFAULT "nucleo_f429zi"
#define MICROPY_PY_SELECT (1)
#define MICROPY_PY_SYS_MODULES (1)
// #define MICROPY_PY_WEBREPL (1)
// #define MICROPY_PY_WEBSOCKET (1)

#undef MICROPY_VFS_FAT
#define MICROPY_VFS_FAT (0)

#undef MICROPY_PY_BUILTINS_PROPERTY
#define MICROPY_PY_BUILTINS_PROPERTY (1)

// #define MICROPY_PY_OS_DUPTERM                   (1)
// #define MICROPY_PY_OS_DUPTERM_NOTIFY            (1)
// #define MICROPY_PY_SSL (1)
// #define MICROPY_PY_SSL_MBEDTLS (1)